version: '3.8'
services:
  postgres:
    container_name: OrderApp
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - ./dump:/var/lib/postgresql/data