// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CustomerInput struct {
	ID         string `json:"id"`
	FirstName  string `json:"firstName"`
	MiddleName string `json:"middleName"`
	LastName   string `json:"lastName"`
	Email      string `json:"email"`
	AddressID  string `json:"addressID"`
}

type CustomerResponse struct {
	ID    string `json:"id"`
	Event string `json:"event"`
}

type SomeQuery struct {
	ID string `json:"id"`
}
