[api]
host = "127.0.0.1"
port = 8002
base_url_prefix = "/api/v1"

[db]
host = "OrderContainerAppTest"
port = 5432
database = "OrderContainerAppTest"
user = "postgres"
password = "1234"
migration = true