# my global config
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'orderService'
    static_configs:
      - targets: [ "orderService.api:8000" ]

  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]